### ISSUE TITLE
Ensuring Accessibility by Using Ethereum Blockchain Based DNS

### ISSUE THREAD

**Issue by michael-spengler** [CryptoLocally/Resources#1]
Hey CryptoLocally Team.

Would it make sense to use something like:
https://unstoppabledomains.com/ or   
https://ens.domains/

to ensure longterm accessibility? 

Kind regards 
Michael

**Comment by jchung00** [comment]
Interesting, we could definitely have a backup domain set up to ensure accessibility. Thanks!
